import type { Metadata } from 'next';
import styles from './layout.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ProductsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <>
    <nav className={styles.nav}>
      <a href="">여성옷</a>
      <a href="">남성옷</a>
    </nav>
    <section className='styles.product'>
      {children}
    </section>
   </>
  )
}
